# Routes

home:
    path:       /
    controller: App\Mail\Controllers\EmailController::home
    methods:    GET

send:
    path:       /send
    controller: App\Mail\Controllers\EmailController::send
    methods:    POST

success:
    path:       /success
    controller: App\Mail\Controllers\EmailController::handle
    methods:    GET

error:
    path:       /error
    controller: App\Mail\Controllers\EmailController::handle
    methods:    GET